// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbowsvxivuxxwoklitvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZib3dzdnhpdnV4eHdva2xpdHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTIwNDYsImV4cCI6MjA2NjUyODA0Nn0.mp9uJamIyGwS1qj-ZfnXhYoL61RgrfRQ9eMzKh5AoTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
